groups:
- name: my_vectors
  rules:
  - record: cpu_usage_perc
    expr: 100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[1m]))  by (instance))
  - record: mem_usage_perc
    expr: 100 * (node_memory_Active_bytes / on (instance) node_memory_MemTotal_bytes)
  - record: disk_usage_perc
    expr: 100 * (node_filesystem_avail_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"} / node_filesystem_size_bytes{fstype!~"tmpfs|fuse.lxcfs|squashfs|vfat"})
  - record: net_kbps
    expr: sum(rate(node_network_transmit_bytes_total[1m])) by (instance) / 1024
